# Generated by Django 5.2.16 on 2026-07-21 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="payment",
            table="me_payments_tbl",
        ),
        migrations.AlterModelTable(
            name="subscription",
            table="me_subscriptions_tbl",
        ),
    ]
