# Generated by Django 5.2.16 on 2026-09-24 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrepCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. SMA 300",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="e.g. Real Analysis I", max_length=200),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Mathematics", "Mathematics"),
                            ("Statistics", "Statistics"),
                            ("Computing", "Computing"),
                            ("Engineering", "Engineering"),
                            ("Business & Economics", "Business & Economics"),
                            ("General Sciences", "General Sciences"),
                            ("Other", "Other"),
                        ],
                        default="Mathematics",
                        max_length=100,
                    ),
                ),
                ("level", models.CharField(default="Undergraduate", max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Canonical course objectives, syllabus scope, and references.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prep Course",
                "verbose_name_plural": "Prep Courses",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PrepDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("Lecture Notes", "Lecture Notes / Module"),
                            (
                                "Continuous Assessment Test (CAT)",
                                "Continuous Assessment Test (CAT)",
                            ),
                            ("Final Examination Paper", "Final Examination Past Paper"),
                            ("Revision Sheet", "Revision Exercises / Tutorial"),
                        ],
                        default="Lecture Notes",
                        max_length=60,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 2024/2025 Semester 1",
                        max_length=100,
                    ),
                ),
                (
                    "topic_name",
                    models.CharField(
                        blank=True, help_text="Topic or unit covered", max_length=255
                    ),
                ),
                ("file", models.FileField(upload_to="prep/documents/%Y/%m/")),
                ("file_size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "github_raw_url",
                    models.URLField(
                        blank=True,
                        help_text="Raw GitHub permanent reference URL",
                        max_length=500,
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True, help_text="Extracted plain text or structured LaTeX"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("stage_1", "Stage 1: Ingestion & Extraction"),
                            ("stage_2", "Stage 2: Tutor Review Gate"),
                            ("stage_3", "Stage 3: Published"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="stage_1",
                        max_length=20,
                    ),
                ),
                (
                    "tutor_review_notes",
                    models.TextField(
                        blank=True,
                        help_text="Feedback or corrections from tutor review gate",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="prep.prepcourse",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_prep_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prep_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prep Document",
                "verbose_name_plural": "Prep Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrepHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("course_code", models.CharField(max_length=50)),
                (
                    "item_type",
                    models.CharField(
                        help_text="e.g. CAT Paper, Lecture Notes, Topic Revision",
                        max_length=60,
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prep_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prep Revision History",
                "verbose_name_plural": "Prep Revision Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrepPaper",
            fields=[
                (
                    "id",
                    models.SlugField(max_length=120, primary_key=True, serialize=False),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Continuous Assessment Test 1 (CAT 1)",
                        max_length=255,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        help_text="e.g. 2024/2025 Semester 1", max_length=100
                    ),
                ),
                ("total_marks", models.PositiveIntegerField(default=30)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        to="prep.prepcourse",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_papers",
                        to="prep.prepdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prep Paper",
                "verbose_name_plural": "Prep Papers",
                "ordering": ["course", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrepTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="LaTeX notes, fundamental theorems, and core formulas.",
                    ),
                ),
                (
                    "subtopics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of subtopics under this unit.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="prep.prepcourse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prep Topic",
                "verbose_name_plural": "Prep Topics",
                "ordering": ["course", "order", "id"],
                "unique_together": {("course", "slug")},
            },
        ),
        migrations.CreateModel(
            name="PrepQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=1)),
                ("marks", models.PositiveIntegerField(default=10)),
                (
                    "topic_label",
                    models.CharField(
                        blank=True,
                        help_text="Topic badge label e.g. Metric Spaces",
                        max_length=150,
                    ),
                ),
                (
                    "question_latex",
                    models.TextField(help_text="LaTeX formatted problem statement"),
                ),
                (
                    "solution_latex",
                    models.TextField(
                        blank=True,
                        help_text="LaTeX step-by-step verified derivation and proof",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified (Tutor / SymPy)"),
                            ("flagged", "Flagged for Correction"),
                        ],
                        default="verified",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="prep.preppaper",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_prep_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="prep.preptopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prep Question",
                "verbose_name_plural": "Prep Questions",
                "ordering": ["paper", "number", "id"],
            },
        ),
        migrations.CreateModel(
            name="PrepContentCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="e.g. topic_notes, solution_derivation, practice_set",
                        max_length=50,
                    ),
                ),
                ("prompt_hash", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("hit_count", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_contents",
                        to="prep.prepcourse",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_contents",
                        to="prep.preptopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prep Content Cache",
                "verbose_name_plural": "Prep Content Caches",
            },
        ),
        migrations.CreateModel(
            name="PrepWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credits_balance", models.PositiveIntegerField(default=250)),
                (
                    "current_plan",
                    models.CharField(
                        choices=[
                            ("basic", "Basic (Starter Prep)"),
                            ("pro", "Pro (Exam Pass)"),
                        ],
                        default="basic",
                        max_length=50,
                    ),
                ),
                ("plan_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prep_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prep Wallet",
                "verbose_name_plural": "Prep Wallets",
            },
        ),
        migrations.CreateModel(
            name="PrepTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Negative for deductions, positive for top-up credits"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("upload_text", "Digital Text PDF Upload (2 credits)"),
                            ("upload_ocr", "Scanned Vision OCR Ingestion (5 credits)"),
                            (
                                "deep_reasoning",
                                "Complex Proof / Derivation (5 credits)",
                            ),
                            ("topup_purchase", "M-Pesa / Paystack Credit Top-Up"),
                            ("monthly_grant", "Monthly Plan Credit Allocation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True,
                        help_text="e.g. M-Pesa transaction ID / Paystack ref",
                        max_length=100,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="prep.prepwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prep Transaction",
                "verbose_name_plural": "Prep Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
