# Generated by Django 5.2.16 on 2026-09-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prep", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prepquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("authentic", "Authentic Past Paper"),
                    ("adapted", "Adapted Past Paper"),
                    ("generated", "AI Generated Variant"),
                ],
                db_index=True,
                default="authentic",
                max_length=20,
            ),
        ),
    ]
