# Generated by Django 5.2.16 on 2026-09-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prep", "0003_prepnotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preptransaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("trial_grant", "3-Day Free Trial Starter Credits"),
                    ("upload_text", "Digital Text PDF Upload (2 credits)"),
                    ("upload_ocr", "Scanned Vision OCR Ingestion (5 credits)"),
                    ("deep_reasoning", "Complex Proof / Derivation (5 credits)"),
                    ("ai_practice_gen", "AI Practice Question Generation"),
                    ("topup_purchase", "M-Pesa / Paystack Credit Top-Up"),
                    ("monthly_grant", "Monthly Plan Credit Allocation"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="prepwallet",
            name="credits_balance",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="prepwallet",
            name="current_plan",
            field=models.CharField(
                choices=[
                    ("trial", "Free Trial (3 Days)"),
                    ("basic", "Basic (Starter Prep)"),
                    ("pro", "Pro (Exam Pass)"),
                ],
                default="trial",
                max_length=50,
            ),
        ),
    ]
