# Generated by Django 5.2.16 on 2026-09-26 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prep", "0004_alter_preptransaction_action_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preptransaction",
            name="input_tokens",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preptransaction",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="preptransaction",
            name="model_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="preptransaction",
            name="output_tokens",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preptransaction",
            name="total_tokens",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="preptransaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("trial_grant", "3-Day Free Trial Starter Credits"),
                    ("upload_text", "Digital Text PDF Upload (2 credits)"),
                    ("upload_ocr", "Scanned Vision OCR Ingestion (5 credits)"),
                    ("deep_reasoning", "Complex Proof / Derivation (5 credits)"),
                    ("ai_practice_gen", "AI Practice Question Generation"),
                    ("topic_notes", "AI Topic Notes Generation"),
                    ("topup_purchase", "M-Pesa / Paystack Credit Top-Up"),
                    ("monthly_grant", "Monthly Plan Credit Allocation"),
                    ("credit_expiry", "Expired Credits"),
                    ("trial_reminder", "Free Trial Reminder"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="prepwallet",
            name="current_plan",
            field=models.CharField(
                choices=[
                    ("trial", "Free Trial (3 Days)"),
                    ("basic", "Basic (Starter Prep)"),
                    ("pro", "Pro (Exam Pass)"),
                    ("expired", "Trial Expired"),
                ],
                default="trial",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PrepCreditGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("trial", "Free Trial"),
                            ("subscription", "Subscription Allocation"),
                            ("purchased", "Purchased Top-Up"),
                            ("admin", "Administrator Grant"),
                            ("legacy", "Legacy Balance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("granted_credits", models.PositiveIntegerField()),
                ("remaining_credits", models.PositiveIntegerField()),
                ("granted_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("reference_code", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_grants",
                        to="prep.prepwallet",
                    ),
                ),
            ],
            options={
                "ordering": ["expires_at", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="preptransaction",
            name="credit_grant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="prep.prepcreditgrant",
            ),
        ),
        migrations.AddIndex(
            model_name="prepcreditgrant",
            index=models.Index(
                fields=["wallet", "source", "expires_at"],
                name="prep_prepcr_wallet__a38fa4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prepcreditgrant",
            index=models.Index(
                fields=["wallet", "remaining_credits"],
                name="prep_prepcr_wallet__b8802d_idx",
            ),
        ),
    ]
