# Generated by Django 5.2.16 on 2026-09-26 23:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prep", "0006_prepcourse_created_by_prepcourse_visibility_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prepcourse",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="prepcourse",
            name="visibility",
        ),
    ]
