# Generated by Django 5.2.16 on 2026-09-26 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prep", "0007_remove_prepcourse_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prepdocument",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicate_documents",
                to="prep.prepdocument",
            ),
        ),
        migrations.AddField(
            model_name="prepdocument",
            name="file_sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="prepdocument",
            name="is_duplicate",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="prepdocument",
            name="text_sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name="PrepContentUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("new_topic", "New Topic"),
                            ("add_subtopics", "Add Missing Subtopics"),
                            ("fill_summary", "Fill Missing Topic Summary"),
                            ("summary_review", "Possible Summary Improvement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("proposed_data", models.JSONField(default=dict)),
                ("rationale", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved and Applied"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_updates",
                        to="prep.prepdocument",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_prep_content_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_updates",
                        to="prep.preptopic",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "created_at"],
            },
        ),
    ]
