# Generated by Django 5.2.16 on 2026-09-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prep", "0008_prepdocument_duplicate_of_prepdocument_file_sha256_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prepcontentupdate",
            name="update_type",
            field=models.CharField(
                choices=[
                    ("new_topic", "New Topic"),
                    ("add_subtopics", "Add Missing Subtopics"),
                    ("fill_summary", "Fill Missing Topic Summary"),
                    ("summary_review", "Possible Summary Improvement"),
                    ("topic_conflict", "Conflicting Topic Identity"),
                ],
                max_length=30,
            ),
        ),
    ]
