# Generated by Django 5.2.16 on 2026-09-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prep", "0009_alter_prepcontentupdate_update_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prepwallet",
            name="current_plan",
            field=models.CharField(
                choices=[
                    ("trial", "Free Trial (3 Days)"),
                    ("basic", "Basic (Starter Prep)"),
                    ("plus", "Plus (Semester Pass)"),
                    ("pro", "Pro (Exam Master)"),
                    ("expired", "Trial Expired"),
                ],
                default="trial",
                max_length=50,
            ),
        ),
    ]
