# Generated by Django 5.2.16 on 2026-09-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prep", "0016_prepnoterepair"),
    ]

    operations = [
        migrations.AddField(
            model_name="prepcourse",
            name="study_profile",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Tutor-approved, source-grounded subject rules for notes and topics.",
            ),
        ),
        migrations.AddField(
            model_name="prepcourse",
            name="study_profile_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="prepcontentupdate",
            name="update_type",
            field=models.CharField(
                choices=[
                    ("course_profile", "Course Study Profile"),
                    ("new_topic", "New Topic"),
                    ("add_subtopics", "Add Missing Subtopics"),
                    ("fill_summary", "Fill Missing Topic Summary"),
                    ("summary_review", "Possible Summary Improvement"),
                    ("topic_conflict", "Conflicting Topic Identity"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="prepcourse",
            name="category",
            field=models.CharField(
                choices=[
                    ("Mathematics", "Mathematics"),
                    ("Statistics", "Statistics"),
                    ("Computing", "Computing"),
                    ("Engineering", "Engineering"),
                    ("Chemistry", "Chemistry"),
                    ("Physics", "Physics"),
                    ("Social Sciences", "Social Sciences"),
                    ("Humanities", "Humanities"),
                    ("Business & Economics", "Business & Economics"),
                    ("General Sciences", "General Sciences"),
                    ("Other", "Other"),
                ],
                default="Mathematics",
                max_length=100,
            ),
        ),
    ]
