# Generated by Django 5.2.16 on 2026-09-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prep", "0017_course_study_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="preptopic",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
