# Generated by Django 5.2.16 on 2026-09-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prep", "0018_activate_profile_topic_retirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="preptopic",
            name="content_rules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Reviewer-approved, source-grounded modality rules for this topic.",
            ),
        ),
        migrations.AddField(
            model_name="preptopic",
            name="content_rules_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="prepcontentupdate",
            name="update_type",
            field=models.CharField(
                choices=[
                    ("course_profile", "Course Study Profile"),
                    ("topic_content_rules", "Topic Content Rules"),
                    ("new_topic", "New Topic"),
                    ("add_subtopics", "Add Missing Subtopics"),
                    ("fill_summary", "Fill Missing Topic Summary"),
                    ("summary_review", "Possible Summary Improvement"),
                    ("topic_conflict", "Conflicting Topic Identity"),
                ],
                max_length=30,
            ),
        ),
    ]
