# Generated by Django 5.2.16 on 2026-09-30 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prep", "0019_preptopic_content_rules_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prepdocument",
            name="page_evidence",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="PrepDocumentVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("page_number", models.PositiveIntegerField(db_index=True)),
                (
                    "bbox",
                    models.JSONField(
                        default=list,
                        help_text="Crop bounds in PDF points: [x0, y0, x1, y1].",
                    ),
                ),
                ("candidate_reasons", models.JSONField(blank=True, default=list)),
                ("context_text", models.TextField(blank=True)),
                (
                    "crop",
                    models.FileField(blank=True, upload_to="prep/visual-crops/%Y/%m/"),
                ),
                (
                    "visual_type",
                    models.CharField(
                        choices=[
                            ("graph", "Graph or Plot"),
                            ("diagram", "Diagram or Flowchart"),
                            ("table", "Table"),
                            ("illustration", "Illustration"),
                            ("unclassified", "Unclassified Visual"),
                        ],
                        default="unclassified",
                        max_length=20,
                    ),
                ),
                ("labels", models.JSONField(blank=True, default=list)),
                ("extracted_content", models.JSONField(blank=True, default=dict)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate Captured"),
                            ("inspected", "Vision Inspected"),
                            ("needs_review", "Needs Review"),
                            ("approved", "Tutor Approved"),
                            ("rejected", "Rejected as Irrelevant"),
                            ("error", "Inspection Error"),
                        ],
                        db_index=True,
                        default="candidate",
                        max_length=20,
                    ),
                ),
                ("vision_model", models.CharField(blank=True, max_length=120)),
                ("vision_usage", models.JSONField(blank=True, default=dict)),
                ("inspection_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visual_candidates",
                        to="prep.prepdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "page_number", "id"],
                "indexes": [
                    models.Index(
                        fields=["document", "page_number", "status"],
                        name="prep_prepdo_documen_d8e754_idx",
                    )
                ],
            },
        ),
    ]
