# Generated by Django 5.2.16 on 2026-10-03 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prep", "0026_prepdocumentvisual_review_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrepCourseSharedCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("upload", "Course Resource Upload"),
                            ("topic_notes", "AI Topic Notes"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("level", models.CharField(blank=True, max_length=20)),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("total_credits", models.PositiveIntegerField()),
                ("per_student_credits", models.PositiveIntegerField()),
                ("member_count_at_creation", models.PositiveIntegerField(default=0)),
                ("usage", models.JSONField(blank=True, default=dict)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_costs",
                        to="prep.prepcourse",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shared_costs",
                        to="prep.prepdocument",
                    ),
                ),
                (
                    "source_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shared_course_cost",
                        to="prep.preptransaction",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shared_costs",
                        to="prep.preptopic",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PrepCourseCostShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required_credits", models.PositiveIntegerField()),
                ("paid_credits", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prep_course_cost_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="prep.prepcoursesharedcost",
                    ),
                ),
            ],
            options={
                "ordering": ["cost__created_at", "cost_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cost", "user"), name="unique_prep_course_cost_share"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PrepNotePrecomputeJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_precompute_jobs",
                        to="prep.prepcourse",
                    ),
                ),
            ],
            options={
                "ordering": ["queued_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "running"])),
                        fields=("course",),
                        name="unique_active_prep_note_precompute_job",
                    )
                ],
            },
        ),
    ]
