# Generated by Django 5.2.16 on 2026-10-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prep", "0027_prepcoursesharedcost_prepcoursecostshare_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="prepnoteprecomputejob",
            name="unique_active_prep_note_precompute_job",
        ),
        migrations.AddConstraint(
            model_name="prepnoteprecomputejob",
            constraint=models.UniqueConstraint(
                fields=("course",), name="unique_prep_note_precompute_course"
            ),
        ),
    ]
