# Generated by Django 5.2.16 on 2026-10-05 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "prep",
            "0028_remove_prepnoteprecomputejob_unique_active_prep_note_precompute_job_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="preptransaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("trial_grant", "3-Day Free Trial Starter Credits"),
                    ("upload_text", "Digital Text PDF Upload (2 credits)"),
                    ("upload_ocr", "Scanned Vision OCR Ingestion (5 credits)"),
                    ("deep_reasoning", "Complex Proof / Derivation (5 credits)"),
                    ("ai_practice_gen", "AI Practice Question Generation"),
                    ("topic_notes", "AI Topic Notes Generation"),
                    ("topic_tutor", "Topic Tutor AI Reply"),
                    ("topic_tutor_ocr", "Topic Tutor Upload OCR"),
                    ("topup_purchase", "M-Pesa / Paystack Credit Top-Up"),
                    ("monthly_grant", "Monthly Plan Credit Allocation"),
                    ("credit_expiry", "Expired Credits"),
                    ("trial_reminder", "Free Trial Reminder"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PrepTopicChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Topic study chat", max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to="prep.preptopic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prep_topic_chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PrepTopicChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Learner"), ("assistant", "Assistant")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("credits_charged", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="prep.preptopicchatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PrepTopicChatUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("extracted_text", models.TextField()),
                ("page_count", models.PositiveIntegerField(default=1)),
                ("source_type", models.CharField(default="text_pdf", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="prep.preptopicchatmessage",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="prep.preptopicchatsession",
                    ),
                ),
            ],
        ),
    ]
