# Generated by Django 5.2.16 on 2026-10-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prep", "0029_alter_preptransaction_action_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrepTopicNotesJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=20)),
                ("source_signature", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_generation_jobs",
                        to="prep.preptopic",
                    ),
                ),
            ],
            options={"ordering": ["queued_at", "id"]},
        ),
        migrations.AddConstraint(
            model_name="preptopicnotesjob",
            constraint=models.UniqueConstraint(
                fields=("topic", "level", "source_signature"),
                name="unique_prep_topic_notes_job",
            ),
        ),
    ]
