# Generated by Django 5.2.16 on 2026-10-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prep", "0030_preptopicnotesjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrepCreditReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purpose", models.CharField(max_length=50)),
                ("reserved_credits", models.PositiveIntegerField()),
                ("remaining_reserved_credits", models.PositiveIntegerField()),
                ("charged_credits", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("settled", "Settled"),
                            ("released", "Released"),
                        ],
                        db_index=True,
                        default="reserved",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_reservations",
                        to="prep.prepwallet",
                    ),
                ),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AddIndex(
            model_name="prepcreditreservation",
            index=models.Index(fields=["wallet", "status"], name="prep_res_wallet_status_idx"),
        ),
    ]
