# Generated by Django 5.2.16 on 2026-07-21 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. 'Week 3: Functions in Python'", max_length=255
                    ),
                ),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=120, help_text="Expected session duration"
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        help_text="Paste Google Meet / Zoom link here", max_length=512
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Any notes for learners before the session",
                    ),
                ),
                (
                    "is_makeup",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a makeup session for a missed live session",
                    ),
                ),
                ("is_cancelled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_sessions",
                        to="courses.cohort",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="The original session this makeup replaces",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="makeups",
                        to="live_sessions.livesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("attended", "Attended"),
                            ("missed", "Missed"),
                            ("excused", "Excused"),
                        ],
                        default="missed",
                        max_length=20,
                    ),
                ),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "learner",
                    models.ForeignKey(
                        limit_choices_to={"role": "learner"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_marked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="live_sessions.livesession",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "learner")},
            },
        ),
    ]
