# Generated by Django 5.2.16 on 2026-07-21 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("live_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="attendance",
            table="me_attendances_tbl",
        ),
        migrations.AlterModelTable(
            name="livesession",
            table="me_live_sessions_tbl",
        ),
    ]
