# Generated by Django 5.2.16 on 2026-07-21 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="guardian",
            table="me_guardians_tbl",
        ),
        migrations.AlterModelTable(
            name="profile",
            table="me_profiles_tbl",
        ),
        migrations.AlterModelTable(
            name="user",
            table="me_users_tbl",
        ),
    ]
