# Generated by Django 5.2.16 on 2026-07-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_guardianlinkrequest_guardianlinkrequestlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="class_level",
            field=models.CharField(
                blank=True,
                help_text="e.g. Primary, JSS, Senior School, Past Senior School, Adult Learner",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="county",
            field=models.CharField(
                blank=True, help_text="County, state, or region", max_length=100
            ),
        ),
    ]
