# Generated by Django 5.2.16 on 2026-07-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_profile_class_level_alter_profile_county"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="experience_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="headline",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="profile",
            name="specialty",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
