# Generated by Django 5.2.16 on 2026-09-05 22:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Short summary of this category"
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        default="book-open",
                        help_text="SVG icon key or name",
                        max_length=50,
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#0f766e",
                        help_text="Theme accent color hex code",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "me_blog_category_tbl",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short teaser summary displayed on cards and social share previews",
                        max_length=500,
                    ),
                ),
                (
                    "markdown_content",
                    models.TextField(
                        help_text="Full article body in Markdown format (# headings, **bold**, *italics*, code blocks, images)"
                    ),
                ),
                (
                    "featured_image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of cover image (GitHub CDN or external URL)",
                        max_length=500,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags (e.g. Python, AI, Beginner)",
                        max_length=255,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this post is visible live on the site",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Pin this article as a featured hero story on the blog home",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("reading_time_minutes", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.category",
                    ),
                ),
            ],
            options={
                "db_table": "me_blog_post_tbl",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
