# Generated by Django 5.2.16 on 2026-09-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image_url",
            field=models.CharField(
                blank=True,
                help_text="URL or path of cover image (GitHub CDN path or external URL)",
                max_length=500,
            ),
        ),
    ]
