# Generated by Django 5.2.16 on 2026-07-21 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "track",
                    models.CharField(
                        choices=[
                            ("tech", "Tech (Programming / ML / AI)"),
                            ("cbc", "CBC Academic (Math, Science, etc.)"),
                            (
                                "specialist",
                                "Specialist (Robotics, Cybersecurity, etc.)",
                            ),
                        ],
                        db_index=True,
                        default="tech",
                        max_length=20,
                    ),
                ),
                (
                    "subject_area",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Mathematics, Python, Robotics",
                        max_length=100,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("JSS1", "Junior Secondary School 1"),
                            ("JSS2", "Junior Secondary School 2"),
                            ("JSS3", "Junior Secondary School 3"),
                            ("Form1", "Form 1"),
                            ("Form2", "Form 2"),
                            ("Form3", "Form 3"),
                            ("Form4", "Form 4"),
                            ("open", "Open / All Levels"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "cover_image_url",
                    models.CharField(
                        blank=True, help_text="GitHub-hosted or CDN URL", max_length=512
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["admin", "tutor"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["track", "title"],
            },
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Batch 1 – Jan 2026' or 'Term 2 2026'",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "schedule_description",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable schedule e.g. 'Saturdays 10am–12pm'",
                        max_length=255,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=30)),
                (
                    "price_kes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly subscription price in KES",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tutor",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["admin", "tutor"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cohorts_teaching",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("expired", "Expired (subscription lapsed)"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes on this enrollment"
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.cohort",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        limit_choices_to={"role": "learner"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_at"],
                "unique_together": {("learner", "cohort")},
            },
        ),
    ]
