# Generated by Django 5.2.16 on 2026-07-21 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cohort",
            table="me_cohorts_tbl",
        ),
        migrations.AlterModelTable(
            name="course",
            table="me_courses_tbl",
        ),
        migrations.AlterModelTable(
            name="enrollment",
            table="me_enrollments_tbl",
        ),
    ]
