# Generated by Django 5.2.16 on 2026-07-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_cohort_table_alter_course_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="name",
            field=models.CharField(
                help_text="e.g. 'Batch 1 - Jan 2026' or 'Term 2 2026'", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="schedule_description",
            field=models.CharField(
                blank=True,
                help_text="Human-readable schedule e.g. 'Saturdays 10am-12pm' or 'Weekdays 7pm-8pm'",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("primary", "Primary School"),
                    ("jss", "Junior Secondary School"),
                    ("senior", "Senior School"),
                    ("past_senior", "Past Senior School"),
                    ("open", "Open / All Levels"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="track",
            field=models.CharField(
                choices=[
                    ("tech", "Tech (Programming / ML / AI)"),
                    ("cbc", "CBE Academic (Math, Science, etc.)"),
                    ("specialist", "Specialist (Robotics, Cybersecurity, etc.)"),
                ],
                db_index=True,
                default="tech",
                max_length=20,
            ),
        ),
    ]
