# Generated by Django 5.2.16 on 2026-07-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0003_alter_cohort_name_alter_cohort_schedule_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="cover_image_url",
            field=models.CharField(
                blank=True,
                help_text="Paste a raw GitHub link or upload below. Saved links are proxied through /cdn/assets/.",
                max_length=512,
            ),
        ),
    ]
