# Generated by Django 5.2.16 on 2026-07-21 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        help_text="Assignment brief — what learners need to do"
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "github_stored_path",
                    models.CharField(
                        blank=True,
                        help_text="Optional PDF brief stored on GitHub",
                        max_length=512,
                    ),
                ),
                ("max_score", models.PositiveIntegerField(default=100)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="content.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="RubricCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. 'Code correctness', 'Presentation'",
                        max_length=255,
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        help_text="Weight in points (criteria weights should sum to max_score)"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What does full marks look like?"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="assignments.assignment",
                    ),
                ),
            ],
            options={
                "ordering": ["assignment", "order"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "github_stored_path",
                    models.CharField(
                        blank=True,
                        help_text="Submitted file stored on GitHub",
                        max_length=512,
                    ),
                ),
                (
                    "text_response",
                    models.TextField(blank=True, help_text="Typed/pasted response"),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        limit_choices_to={"role": "learner"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("assignment", "learner")},
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.DecimalField(decimal_places=2, max_digits=6)),
                ("tutor_comment", models.TextField(blank=True)),
                ("graded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grades_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade",
                        to="assignments.submission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CriterionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=6)),
                ("comment", models.TextField(blank=True)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterion_scores",
                        to="assignments.grade",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="assignments.rubriccriterion",
                    ),
                ),
            ],
            options={
                "unique_together": {("grade", "criterion")},
            },
        ),
    ]
