# Generated by Django 5.2.16 on 2026-07-21 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="assignment",
            table="me_assignments_tbl",
        ),
        migrations.AlterModelTable(
            name="criterionscore",
            table="me_criterion_scores_tbl",
        ),
        migrations.AlterModelTable(
            name="grade",
            table="me_grades_tbl",
        ),
        migrations.AlterModelTable(
            name="rubriccriterion",
            table="me_rubric_criteria_tbl",
        ),
        migrations.AlterModelTable(
            name="submission",
            table="me_submissions_tbl",
        ),
    ]
