# Generated by Django 5.2.16 on 2026-07-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "assignments",
            "0002_alter_assignment_table_alter_criterionscore_table_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="description",
            field=models.TextField(
                help_text="Assignment brief - what learners need to do"
            ),
        ),
    ]
