# Generated by Django 5.2.16 on 2026-07-21 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="lesson",
            table="me_lessons_tbl",
        ),
        migrations.AlterModelTable(
            name="lessonprogress",
            table="me_lesson_progress_tbl",
        ),
        migrations.AlterModelTable(
            name="resource",
            table="me_resources_tbl",
        ),
        migrations.AlterModelTable(
            name="videoasset",
            table="me_video_assets_tbl",
        ),
    ]
