# Generated by Django 5.2.16 on 2026-07-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_lesson_table_alter_lessonprogress_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoasset",
            name="github_stored_path",
            field=models.CharField(
                blank=True,
                help_text="Stored path in GitHub repository for fallback video streaming",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="videoasset",
            name="bunny_video_id",
            field=models.CharField(
                blank=True,
                help_text="Bunny Stream video GUID or fallback identifier",
                max_length=255,
            ),
        ),
    ]
