# Generated by Django 5.2.16 on 2026-07-23 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_videoasset_github_stored_path_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonprogress",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("submitted", "Pending Verification"),
                    ("verified", "Verified & Completed"),
                    ("rejected", "Returned by Tutor"),
                ],
                db_index=True,
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="student_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_lesson_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="completed",
            field=models.BooleanField(
                default=False, help_text="True once verified by tutor"
            ),
        ),
    ]
